### ISSUE TITLE
Problem granting user access to a specific schema

### ISSUE THREAD

**Issue by shivansh2785** [ibm-cloud-docs/Db2whc#10]
I added a new user to my Db2 instance, gave him access to SYSCAT schema using -
**GRANT SELECTIN ON SCHEMA "SYSCAT" TO USER "<username>"**

and then gave him access to an schema using -
**GRANT DATAACCESS,ALTERIN, CREATEIN, DELETEIN, DROPIN, EXECUTEIN, INSERTIN, SELECTIN, UPDATEIN ON SCHEMA "PALANTIR" TO USER "<username>"**

but on creating a new table, the user gets this error -
"<username>" does not have the privilege to perform operation "CREATE TABLE"..

On running **select * from syscat.schemaauth**, it shows Y for user in CREATEINAUTH column for that schema.

**Comment by shivansh2785** [comment]
@rimask any help on this..

**Comment by rimask** [comment]
Issues opened here are for documentation errors or suggestions for doc improvements. This is not for Support issues.

For Support issues, see the following topic:
https://cloud.ibm.com/docs/Db2whc?topic=Db2whc-help_support#gettinghelp
