### ISSUE TITLE
Need to know migration of clob object from local db2 to ibm cloud

### ISSUE THREAD

**Issue by dillibabu77** [ibm-cloud-docs/Db2whc#3]
**Create statement:**

CREATE TABLE "SMS_APP_WEB"."PROFILE_CONFIG" ("USER_ID" VARCHAR(100) NOT NULL , "JSON_CONFIGURATION" CLOB(3M), "DEFAULT_PROFILE" VARCHAR(1), "PROFILE_NAME" VARCHAR(100), "PROFILE_ID" BIGINT  NOT NULL GENERATED ALWAYS AS IDENTITY(START WITH 1,INCREMENT BY 1,NO CACHE), "CREATED_DATE" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, "LASTUPDATED" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,PRIMARY KEY("PROFILE_ID") ) ;

**Export statement:**

export to /home/db2inst1/LocalServer/prdbackupwithincre/profile_config.ixf of ixf LOBS TO '/home/db2inst1/LocalServer/prdbackupwithincre/Lobs/profile' LOBFILE lOBFILES modified by lobsinfile  messages /home/db2inst1/LocalServer/prdbackupwithincre/profilemessage.txt SELECT USER_ID,PROFILE_ID,JSON_CONFIGURATION,DEFAULT_PROFILE,PROFILE_NAME,CREATED_DATE FROM SMS_APP_WEB.PROFILE_CONFIG

**Import statement_**

 db2 'load client From "/home/db2inst1/LocalServer/prdbackupwithincre/profile_config.ixf" of ixf LOBS from '/home/db2inst1/LocalServer/prdbackupwithincre/Lobs/profile' MODIFIED by lobsinfile IDENTITYOVERRIDE MESSAGES /home/db2inst1/LocalServer/prdbackupwithincre/profileImportmessage.txt INSERT INTO SMS_APP_WEB.PROFILE_CONFIG ("USER_ID","PROFILE_ID","JSON_CONFIGURATION", "DEFAULT_PROFILE", "PROFILE_NAME","CREATED_DATE")'

**Details**

At present when i run to load local db2 data to ibm db2warehouse of a table which clob, it is not importing. i am getting the following error
SQL3153N  The T record in the PC/IXF file has name 
"/home/db2inst1/LocalServer/prdbackupwithincre/profile_co", qualifier "", and 
source "            ".

SQL3519W  Begin Load Consistency Point. Input record count = "0".

SQL3520W  Load Consistency Point was successful.

SQL3229W  The field value in row "1" and column "3" is invalid. The row was 
rejected. Reason code: "1".

SQL3185W  The previous error occurred while processing data from row "1" of 
the input file.

SQL3110N  The utility has completed processing.  "1" rows were read from the 
input file.

SQL3519W  Begin Load Consistency Point. Input record count = "1".

SQL3520W  Load Consistency Point was successful.

SQL3515W  The utility has finished the "LOAD" phase at time "01/21/2020 
06:23:08.291262".

**Comment by rimask** [comment]
@dillibabu77 
I'm sorry that you're experiencing problems loading clob objects to your IBM Db2 Warehouse on Cloud database service. However, this is not the place to get support for IBM Cloud service problems. This doc repo is to correct problems with existing documentation. For information about how to get answers to your support questions, please see the following topic:
https://cloud.ibm.com/docs/services/Db2whc?topic=Db2whc-help_support
