### ISSUE TITLE
Update cli_deploy.md

### ISSUE THREAD

**Issue by ochmanmi** [ibm-cloud-docs/Db2whc#5]
Can the documentation be updated for deploying service with IBM Cloud CLI:

https://github.com/ibm-cloud-docs/Db2whc/blob/master/cli_deploy.md ?

After migration to resource groups provided documentation is deprecated and no longer works. 
Customers have problems finding correct way to order service with json parameters like specifying datacenter or selecting high availability option with **ibmcloud resource service-instance-create** command.

**Comment by rimask** [comment]
@ochmanmi 
The Db2 Warehouse on Cloud CLI instructions are for Cloud Foundry services and are correct. Db2 Warehouse on Cloud does not support Resource Groups (RGs).

When Db2 Warehouse on Cloud supports RGs, the instructions will be updated.
