### ISSUE TITLE
POST /dbapi/v4/schema_discovery - 500 Internal Server Error

### ISSUE THREAD

**Issue by mkchrist** [ibm-cloud-docs/Db2whc#6]
Hello,

I am trying to load a CSV file on IBM Cloud Pak, and I am getting the following error at the stage where I select "new table"

POST /dbapi/v4/schema_discovery - 500 Internal Server Error

Does anyone have an idea when this will be fixed?

**Comment by rimask** [comment]
@mkchrist 
Issues opened here are for documentation change requests and not for support issues.

Please see the following documentation regarding how to get help and support:
https://cloud.ibm.com/docs/Db2whc?topic=Db2whc-help_support
